version: '3.8'

services:
  face-recognition:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./dataset:/app/dataset
      - ./captures:/app/captures
      - ./logs:/app/logs
      - ./people_info.json:/app/people_info.json
    environment:
      - FLASK_ENV=development
      - DEBUG=True
      - HOST=0.0.0.0
      - PORT=5000
    restart: unless-stopped
    
  # Optional: Add a database service for production
  # redis:
  #   image: redis:alpine
  #   restart: unless-stopped
  #   volumes:
  #     - redis_data:/data
  
# volumes:
#   redis_data:
